# This file was generated by GoReleaser. DO NOT EDIT.
cask "kitlegal" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "093e336e1e8d6345a3efc96c7aa8ce0f41ea3b791c65f029c78525ced222faf8"
      url "https://github.com/jmorenobl/kitlegal/releases/download/v#{version}/kitlegal_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e47265dbb2d41e8c5e9d54c8c1b0439d4fb32cde3b3ff44a970e49538015df58"
      url "https://github.com/jmorenobl/kitlegal/releases/download/v#{version}/kitlegal_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0a2423e945bb5fef45b5fbdfae619790c13ef70079e9d9968867415ec9ac4406"
      url "https://github.com/jmorenobl/kitlegal/releases/download/v#{version}/kitlegal_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0b18b1dc208353ebc543914884133e39f7883d8d9127d7182ab2d236fcda9d6d"
      url "https://github.com/jmorenobl/kitlegal/releases/download/v#{version}/kitlegal_linux_amd64.tar.gz"
    end
  end

  name "kitlegal"
  desc "Consulta fuentes legales públicas españolas desde skills agénticas"
  homepage "https://github.com/jmorenobl/kitlegal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kitlegal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kitlegal"]
    end
  end

  # No zap stanza required
end
