# This file was generated by GoReleaser. DO NOT EDIT.
cask "kitlegal" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "67dc774030161c16232f02c888ffcd15f7710a0808db0686b3bec5b11caffd09"
      url "https://github.com/jmorenobl/kitlegal/releases/download/v#{version}/kitlegal_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6507404a8812fa398277f9768f7e1847a8abb30483e2b808e685ff747a1c4168"
      url "https://github.com/jmorenobl/kitlegal/releases/download/v#{version}/kitlegal_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4ac527164ac451e7272f58abffcab7aad4b7b2d4bc8eb753c5bcccf1ec6216ee"
      url "https://github.com/jmorenobl/kitlegal/releases/download/v#{version}/kitlegal_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f64361539d3b31caad07068d0448df46804ff1b1dd2d3d70770d85d77d780074"
      url "https://github.com/jmorenobl/kitlegal/releases/download/v#{version}/kitlegal_linux_amd64.tar.gz"
    end
  end

  name "kitlegal"
  desc "Tu asistente de IA responde con la ley vigente del BOE y la cita exacta"
  homepage "https://github.com/jmorenobl/kitlegal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kitlegal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kitlegal"]
    end
  end

  # No zap stanza required
end
