# This file was generated by GoReleaser. DO NOT EDIT.
cask "kitlegal" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "77f239cb2e2620d90e65775fdd5e2c9b741efda82ea897c058b924ab4827dc3b"
      url "https://github.com/jmorenobl/kitlegal/releases/download/v#{version}/kitlegal_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e51062cf020111f569b5772b28824a125c392ba04644cfb70e30ea3dfe5acaa4"
      url "https://github.com/jmorenobl/kitlegal/releases/download/v#{version}/kitlegal_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ac38269ad0bd78a1695cc4010a15c30ca027d652efd6d780b4420108bdcf57fe"
      url "https://github.com/jmorenobl/kitlegal/releases/download/v#{version}/kitlegal_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "73eefb9fa1f72153422ef304a6404bf4c4e89a876f10bd49c621806dc0889fef"
      url "https://github.com/jmorenobl/kitlegal/releases/download/v#{version}/kitlegal_linux_amd64.tar.gz"
    end
  end

  name "kitlegal"
  desc "Tu asistente de IA responde con la ley vigente del BOE y la cita exacta"
  homepage "https://github.com/jmorenobl/kitlegal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kitlegal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kitlegal"]
    end
  end

  # No zap stanza required
end
